/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiParseCvRouteImport } from './routes/api/parse-cv'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiAppDataRouteImport } from './routes/api/app-data'
import { Route as ApiDocumentSplatRouteImport } from './routes/api/document/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParseCvRoute = ApiParseCvRouteImport.update({
  id: '/api/parse-cv',
  path: '/api/parse-cv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppDataRoute = ApiAppDataRouteImport.update({
  id: '/api/app-data',
  path: '/api/app-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentSplatRoute = ApiDocumentSplatRouteImport.update({
  id: '/api/document/$',
  path: '/api/document/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/api/app-data': typeof ApiAppDataRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/parse-cv': typeof ApiParseCvRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/document/$': typeof ApiDocumentSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/api/app-data': typeof ApiAppDataRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/parse-cv': typeof ApiParseCvRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/document/$': typeof ApiDocumentSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/api/app-data': typeof ApiAppDataRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/parse-cv': typeof ApiParseCvRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/document/$': typeof ApiDocumentSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/api/app-data'
    | '/api/generate'
    | '/api/parse-cv'
    | '/api/upload'
    | '/api/auth/$'
    | '/api/document/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/api/app-data'
    | '/api/generate'
    | '/api/parse-cv'
    | '/api/upload'
    | '/api/auth/$'
    | '/api/document/$'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/api/app-data'
    | '/api/generate'
    | '/api/parse-cv'
    | '/api/upload'
    | '/api/auth/$'
    | '/api/document/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  LoginRoute: typeof LoginRoute
  ApiAppDataRoute: typeof ApiAppDataRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiParseCvRoute: typeof ApiParseCvRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDocumentSplatRoute: typeof ApiDocumentSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse-cv': {
      id: '/api/parse-cv'
      path: '/api/parse-cv'
      fullPath: '/api/parse-cv'
      preLoaderRoute: typeof ApiParseCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/app-data': {
      id: '/api/app-data'
      path: '/api/app-data'
      fullPath: '/api/app-data'
      preLoaderRoute: typeof ApiAppDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document/$': {
      id: '/api/document/$'
      path: '/api/document/$'
      fullPath: '/api/document/$'
      preLoaderRoute: typeof ApiDocumentSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  LoginRoute: LoginRoute,
  ApiAppDataRoute: ApiAppDataRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiParseCvRoute: ApiParseCvRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDocumentSplatRoute: ApiDocumentSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
